cache:
  directories:
    - $HOME/.stack

# https://docs.haskellstack.org/en/stable/install_and_upgrade/
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- curl -sSL https://get.haskellstack.org/ | sh
- stack --version

install:
- stack --no-terminal test --only-dependencies

script:
- echo $TRAVIS_TAG
- "GHC_OPTIONS=\"--ghc-options=\"$(ruby -e 'print (ENV[%q|TRAVIS_TAG|] =~ /v/ ? %q|-O3| : %q|-O0|)')\"\""
- echo $GHC_OPTIONS
- stack --no-terminal haddock --test --no-haddock-deps --pedantic -j 4 $GHC_OPTIONS

deploy:
- provider: releases
  api_key:
    secure: "qL3CEhSjjNz+vxayyCxQKFmLlHqSlafZLf3M1kqpA0DF0vX4iAKBZi3LUX+Ir6tUA06EBfbFP/YaogSNk4k7vNYC247csM7673zta8sJYMKPecCWibEM4JHK+f9VrLyEKYETNBCC0nkntCJnWVVL9Nk1hzI7KnvO1XrLkSkVPMhrUsygLZZlNmOkbiCTC49s1wGKBhcsEmZAcq2PvE7nRF/eh+0KWUJJqwBSrOXVDnkPQIfOOC91EZoXEgmk2X/P4gV6k6fRtSIedZwGAbmvM7/iMhFDGPuWgMh4I4ccAkNJKmtKFqqloWlwfB23wUMNDCPmU1Su9YEYyIqv6mWMZ1/DaE88Yxc9Kb6QFLaFfSVs8NS2Uxka4XIVtvywD7p9e3asjkCRE/nJbJ0AJCdmVEqIsYJUsZn7Y4Bge7/wu0AY9GXrihX7bVo7fNdJu0IC/Ad0jtR+PHlClITkQxiNkmLBI0ZUzTeqBVO4dAzHiYrqp6LwmrLDBcd0wPoaCIZHoZqyQCUm5mqhvhGpMH2twFUHikyTeIW1zW4OREuhFv4OwisvVkRAHXIttyEivGZ3H6TmlKtBSV8eOi7nTABA48gN6VVKIhjwXsGPAW0Sqi8M/zw1g6pCtoI85mTqvu6sW9Nc8hKefBUBzvUkLugMyvNGPp6EmkK6wRLSxa0W+bM="
  on:
    repo: camfort/fortran-src
    tags: true
- provider: hackage
  username: madgen
  file:
  password:
    secure: "rPHxI/rLJZ2FeIXfu9Ul/xpDcktS2r85Fb8YH+huM9gJAlYjUYoLmxC4+NVo8AnkU3vn4CyhLSJjGCXW39Ajfz4vr1CQ7V/fieQlKl7J93O+MCrasgl6cn/X2AfZZX59fp3Xrv5K+ldKzuNETUCZqpfpF9KxvSijG1+GEAW8YQDVOssdgA1BMJRR9tVpGZvMkqaRE1jRjYOGsEArEA7OK0lNxwn1hb8ey3MW6bq1K+RkIzhy4uXudfyXu0Z4vw57y+yN+v1Yk71IXQuGhMprXMMXWxMN2NRPsEskkSgATJylUYIZ3q+Z9VWIHdt0a3cYEy6095UeMe/NbNVER4HqAV5RX0ZWPynbQW38bdUF3yhICtl6gm4/4rZ+GiUpkaDXebqcngRA7B7i3v98k9OqfFFTTDtMRwrmETIXrZs/E1DHVSEqvxNI9/kiAmD9lXtYiLeKfdTQr+Lk7gtPl0Fw6NzOSA0N+ZVGRjJlYZbSfoHnWAlJIF8pD3Wh01UDGylqmRAYI0fnGwKPK2nGsOq1CM6fkrKAD7JGHIRsyBQ7JLixOL+12jXHZD0JODsQQAgAavD4eCZgFI2HbjfXgBHhdwQPbscE0wqsUdTsluKmvECIhy3b+tmZPfEURR7JPj5bsrpxh9o6ne6PCcLle30ImLwTz80M8GnmShQOPuQHS+M="
  on:
    repo: camfort/fortran-src
    tags: true
